---
- name: Set MOTD for Proxy servers
  hosts: proxy
  become: true
  tasks:
    - name: Set MOTD for Proxy servers
      ansible.builtin.copy:
        content: "Welcome to HAProxy server"
        dest: /etc/motd

- name: Set MOTD for Webserver servers
  hosts: webservers
  become: true
  tasks:
    - name: Set MOTD for Webserver servers
      ansible.builtin.copy:
        content: "Welcome to Apache server"
        dest: /etc/motd

- name: Set MOTD for Database servers
  hosts: database
  become: true
  tasks:
    - name: Set MOTD for Database servers
      ansible.builtin.copy:
        content: "Welcome to MySQL server"
        dest: /etc/motd

