---
- name: SSHd configuration for all hosts
  hosts: all
  become: true

  tasks:
    - name: Set SSHd banner
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
        backup: true
      loop:
        - { regexp: '^#? *Banner', line: 'Banner /etc/motd' }
        - { regexp: '^#? *X11Forwarding', line: 'X11Forwarding no' }
        - { regexp: '^#? *MaxAuthTries', line: 'MaxAuthTries 3' }
      notify: Restart sshd service
 
  handlers:
    - name: Restart sshd service
      ansible.builtin.systemd_service:
        service: sshd
        state: restarted
